<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->
<!DOCTYPE memberList
[
<!ELEMENT memberList (memberInfo+)> 
<!ELEMENT memberInfo (name, telephone, curriculumn?, zipCode, addr)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT curriculumn (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT addr (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>
]>

<!-- #REQUIRED : 이 속성음 반드시 명시되어야 한다 -->
<!-- #IMPLIED : 이 속성은 명시되기도 하고, 명시되지 않기도 한다. -->
<!-- #FIXED 특정값 : 이 속성은 특정값으로 고정되어 사용된다. -->

<memberList>
	<memberInfo mid="1">
		<name>이연주</name>
		<telephone><![CDATA[010-4423-0463]]></telephone>
		<curriculumn>
			<sub>JAVA</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Spring&xml]]></sub>
		</curriculumn>
		<zipCode>1234</zipCode>
		<addr>충북 청주시 가경동 태암수정아파트</addr>
	</memberInfo>
	
	<memberInfo mid="2">
		<name>홍길동</name>
		<telephone><![CDATA[010-1123-1234]]></telephone>
		<curriculumn>
			<sub>JAVA</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Spring&xml]]></sub>
		</curriculumn>
		<zipCode>1234</zipCode>
		<addr>강원도 원주시 어쩌구</addr>
	</memberInfo>
</memberList>